spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springdb
    username: springuser
    password: spring123

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080